# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_actionlistitem_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pk']},
        ),
    ]
