language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"
matrix:
    allow_failures:
        - python: "3.5-dev"
        - python: "nightly"
services:
    - postgresql
addons:
    postgresql: "9.3"
env:
    global:
        - DJANGO_SETTINGS_MODULE="projman.settings.ci"
sudo: false
install:
    - pip install -r requirements/ci.txt
    - pip install coveralls
before_script:
    # set up postgresql
    - psql -c "CREATE DATABASE projman_ci" -U postgres
script:
    # All translations should compile without problems
    - python manage.py compilemessages
    - coverage run -p manage.py test landing
    - coverage run -p manage.py test projects
    - coverage run -p manage.py test settings
    - coverage run -p manage.py test functional_tests
    # Run tests in reverse to ensure test independence
    - python manage.py test landing --reverse
    - python manage.py test projects --reverse
    - python manage.py test settings --reverse
    - python manage.py test functional_tests --reverse
after_success:
    - "coverage combine && coveralls"
