language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"
services:
    - postgresql
addons:
    postgresql: "9.3"
env:
    global:
        - DJANGO_SETTINGS_MODULE="projman.settings.ci"
sudo: false
install:
    - pip install -r requirements/test.txt
    - pip install coveralls
before_script:
    # set up postgresql
    - psql -c "CREATE_DATABASE projman_ci" -U postgres
    # start svfb
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # allow xvfb some time to start
script:
    - coverage run -p manage.py test landing
    - coverage run -p manage.py test functional_tests
    # Run tests in reverse to ensure test independence
    - python manage.py test landing --reverse
    - python manage.py test functional_tests --reverse
after_success:
    - "coverage combine && coveralls"
